[
    { "id": 1, "nombre": "Tacos", "descripcion": "Tortilla de maíz rellena de carne, salsa y vegetales.", "categoria": "Plato Principal" },
    { "id": 2, "nombre": "Sushi", "descripcion": "Arroz adobado acompañado de pescado crudo o mariscos.", "categoria": "Plato Principal" },
    { "id": 3, "nombre": "Pizza Margherita", "descripcion": "Pizza con salsa de tomate, queso mozzarella y albahaca.", "categoria": "Plato Principal" },
    { "id": 4, "nombre": "Paella", "descripcion": "Arroz cocido con mariscos, pollo, conejo y verduras.", "categoria": "Plato Principal" },
    { "id": 5, "nombre": "Pad Thai", "descripcion": "Fideos de arroz salteados con camarones, tofu y maní.", "categoria": "Plato Principal" },
    { "id": 6, "nombre": "Falafel", "descripcion": "Bolas fritas de garbanzos o habas con especias.", "categoria": "Aperitivo" },
    { "id": 7, "nombre": "Croissant", "descripcion": "Pan dulce hojaldrado de origen francés.", "categoria": "Panadería" },
    { "id": 8, "nombre": "Empanadas", "descripcion": "Masa rellena de carne, pollo, o queso y frita u horneada.", "categoria": "Aperitivo" },
    { "id": 9, "nombre": "Bratwurst", "descripcion": "Salchicha alemana hecha de carne de cerdo y ternera.", "categoria": "Plato Principal" },
    { "id": 10, "nombre": "Moussaka", "descripcion": "Plato griego de capas de berenjena, carne y salsa bechamel.", "categoria": "Plato Principal" },
    { "id": 11, "nombre": "Ceviche", "descripcion": "Pescado crudo marinado en jugo de limón con cebolla y ají.", "categoria": "Plato Principal" },
    { "id": 12, "nombre": "Gyoza", "descripcion": "Empanadillas japonesas rellenas de carne o vegetales.", "categoria": "Aperitivo" },
    { "id": 13, "nombre": "Kebab", "descripcion": "Carne asada en un pincho servida en pan o con arroz.", "categoria": "Plato Principal" },
    { "id": 14, "nombre": "Biryani", "descripcion": "Arroz especiado con carne, pescado o vegetales de la India.", "categoria": "Plato Principal" },
    { "id": 15, "nombre": "Churros", "descripcion": "Dulce frito en forma de bastón espolvoreado con azúcar.", "categoria": "Postre" },
    { "id": 16, "nombre": "Fondue", "descripcion": "Plato suizo de queso derretido acompañado de pan.", "categoria": "Plato Principal" },
    { "id": 17, "nombre": "Poutine", "descripcion": "Papas fritas cubiertas con queso y salsa gravy.", "categoria": "Plato Principal" },
    { "id": 18, "nombre": "Goulash", "descripcion": "Estofado húngaro de carne con pimentón y especias.", "categoria": "Plato Principal" },
    { "id": 19, "nombre": "Tiramisu", "descripcion": "Postre italiano con capas de café, crema de mascarpone y cacao.", "categoria": "Postre" },
    { "id": 20, "nombre": "Dim Sum", "descripcion": "Variedad de pequeños platos chinos al vapor o fritos.", "categoria": "Aperitivo" },
    { "id": 21, "nombre": "Pho", "descripcion": "Sopa vietnamita de fideos de arroz con carne y hierbas.", "categoria": "Plato Principal" },
    { "id": 22, "nombre": "Kimchi", "descripcion": "Col fermentada con especias coreanas.", "categoria": "Acompañamiento" },
    { "id": 23, "nombre": "Arepas", "descripcion": "Pan plano de maíz, típico de Venezuela y Colombia.", "categoria": "Plato Principal" },
    { "id": 24, "nombre": "Pasta Carbonara", "descripcion": "Plato de pasta con huevo, queso y panceta.", "categoria": "Plato Principal" },
    { "id": 25, "nombre": "Macarons", "descripcion": "Pequeños dulces franceses hechos con clara de huevo y almendra.", "categoria": "Postre" },
    { "id": 26, "nombre": "Enchiladas", "descripcion": "Tortillas de maíz rellenas de carne y bañadas en salsa.", "categoria": "Plato Principal" },
    { "id": 27, "nombre": "Baklava", "descripcion": "Dulce turco con capas de masa filo, nueces y miel.", "categoria": "Postre" },
    { "id": 28, "nombre": "Baba Ganoush", "descripcion": "Puré de berenjena con ajo, aceite de oliva y tahini.", "categoria": "Acompañamiento" },
    { "id": 29, "nombre": "Borscht", "descripcion": "Sopa de remolacha típica de Europa del Este.", "categoria": "Plato Principal" },
    { "id": 30, "nombre": "Döner", "descripcion": "Carne asada en rodajas finas, servida en pan o con ensaladas.", "categoria": "Plato Principal" },
    { "id": 31, "nombre": "Gumbo", "descripcion": "Sopa criolla con mariscos o pollo, típica de Luisiana.", "categoria": "Plato Principal" },
    { "id": 32, "nombre": "Samosas", "descripcion": "Empanadillas fritas rellenas de papas o carne con especias.", "categoria": "Aperitivo" },
    { "id": 33, "nombre": "Tom Yum", "descripcion": "Sopa tailandesa picante con camarones y hierbas frescas.", "categoria": "Plato Principal" },
    { "id": 34, "nombre": "Fajitas", "descripcion": "Carne asada con pimientos y cebollas servida en tortilla.", "categoria": "Plato Principal" },
    { "id": 35, "nombre": "Ramen", "descripcion": "Sopa japonesa de fideos con caldo y carne o vegetales.", "categoria": "Plato Principal" },
    { "id": 36, "nombre": "Feijoada", "descripcion": "Guiso brasileño de frijoles negros con carne.", "categoria": "Plato Principal" },
    { "id": 37, "nombre": "Pierogi", "descripcion": "Dumplings polacos rellenos de papas, queso o carne.", "categoria": "Aperitivo" },
    { "id": 38, "nombre": "Cassoulet", "descripcion": "Estofado francés de frijoles con salchichas y carne.", "categoria": "Plato Principal" },
    { "id": 39, "nombre": "Ratatouille", "descripcion": "Guiso francés de vegetales como berenjenas, calabacines y tomates.", "categoria": "Plato Principal" },
    { "id": 40, "nombre": "Chow Mein", "descripcion": "Fideos chinos salteados con carne y vegetales.", "categoria": "Plato Principal" },
    { "id": 41, "nombre": "Sachertorte", "descripcion": "Pastel de chocolate austriaco con mermelada de albaricoque.", "categoria": "Postre" },
    { "id": 42, "nombre": "Pollo Tandoori", "descripcion": "Pollo marinado en yogur y especias, cocido en horno tandoor.", "categoria": "Plato Principal" },
    { "id": 43, "nombre": "Focaccia", "descripcion": "Pan italiano con aceite de oliva y hierbas.", "categoria": "Panadería" },
    { "id": 44, "nombre": "Papas Bravas", "descripcion": "Papas fritas servidas con salsa picante, típicas de España.", "categoria": "Aperitivo" },
    { "id": 45, "nombre": "Couscous", "descripcion": "Sémola de trigo cocida al vapor, típica de Marruecos.", "categoria": "Acompañamiento" },
    { "id": 46, "nombre": "Mochi", "descripcion": "Dulce japonés hecho de arroz glutinoso relleno de pasta de frijoles.", "categoria": "Postre" },
    { "id": 47, "nombre": "Pavlova", "descripcion": "Postre de merengue con crema y frutas, popular en Australia y Nueva Zelanda.", "categoria": "Postre" },
    { "id": 48, "nombre": "Calzone", "descripcion": "Pizza doblada y horneada, rellena de queso, tomate y embutidos.", "categoria": "Plato Principal" },
    { "id": 49, "nombre": "Shawarma", "descripcion": "Carne asada en rodajas finas, servida en pan de pita.", "categoria": "Plato Principal" },
    { "id": 50, "nombre": "Gelato", "descripcion": "Helado italiano cremoso con diversos sabores.", "categoria": "Postre" }
]
